# Generated by Django 4.1.7 on 2023-02-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prducts',
            field=models.ManyToManyField(related_name='orders', to='shopapp.product'),
        ),
    ]
