# Generated by Django 4.1.7 on 2023-02-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_order_prducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prducts',
            new_name='products',
        ),
    ]
